### ISSUE TITLE
Photography Our Portfolio – preview of images on either side has disappeared after uploading a batch of my own images

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#18]
<img width="1502" alt="Screenshot 2023-06-22 at 6 54 51 pm" src="https://github.com/markendley/pprjne/assets/137390062/8b425967-f541-441e-9395-f61d2d344b9a">

**Comment by markendley** [comment]
fixed

**Comment by jillian-sun** [comment]
Sorry i noticed this is still an issue on the photo booth page 
<img width="1920" alt="Screenshot 2023-07-07 at 1 26 24 pm" src="https://github.com/markendley/pprjne/assets/137390062/f0beab7a-6bee-4f31-8bb2-f1170a90d57f">

**Comment by markendley** [comment]
Oh, it's because I changed it so it'll show portrait as well as landscape...

**Comment by markendley** [comment]
just made some small tweaks so you're more likely to see those things coming from the side

how do you like that?

**Comment by jillian-sun** [comment]
looks amazing, thanks mark
